apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: liftnotebook-db
  namespace: liftnotebook
spec:
  teamId: liftnotebook
  numberOfInstances: 1
  postgresql:
    version: "15"
  users:
    liftnotebook_app: []
  databases:
    liftnotebook: liftnotebook_app
  patroni:
    pg_hba:
      - local   all             postgres                          trust
      - local   replication     standby                           trust
      - host    replication     standby         0.0.0.0/0         md5
      - host    all             all             0.0.0.0/0         md5
  volume:
    size: 1Gi
