{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "microservice.fullname" . }}
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "microservice.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
{{- end }}
