apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - exerciselib-service.yaml
  - exerciselib-deployment.yaml
  - libconsole-service.yaml
  - libconsole-deployment.yaml
  - workouttracker-service.yaml
  - workouttracker-deployment.yaml
  - webapp-service.yaml
  - webapp-deployment.yaml
