apiVersion: apps/v1
kind: Deployment
metadata:
  name: libconsole
  namespace: exerciselib
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: libconsole
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: libconsole
    spec:
      containers:
        - name: libconsole
          image: ghcr.io/jcroyoaun/libconsole:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
