replicaCount: 2

image:
  repository: 443311183770.dkr.ecr.us-east-1.amazonaws.com/exerciselib
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: "exerciselib"
fullnameOverride: "exerciselib"

statefulSet:
  enabled: false

serviceAccount:
  create: false

service:
  type: ClusterIP
  port: 4000
  targetPort: 4000

ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /v1/healthcheck
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    external-dns.alpha.kubernetes.io/hostname: exerciselib.liftnotebook.jcroyoaun.com
  hosts:
    - host: exerciselib.liftnotebook.jcroyoaun.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  EXERCISELIB_DB_DSN: "" 

probes:
  liveness:
    enabled: true
    httpGet:
      path: /v1/healthcheck
      port: 4000
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    enabled: true
    httpGet:
      path: /v1/healthcheck
      port: 4000
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
