apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - exerciselib-gateway.yaml
  - exerciselib-virtualservice.yaml
  - liftnotebook-gateway.yaml
  - liftnotebook-virtualservice.yaml
