{{- if .Values.service.configFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.fullname" . }}-config-file
data:
  {{- range $filename, $content := .Values.service.configFiles }}
  {{ $filename }}: |
{{ $content | indent 4 }}
  {{- end }}
{{- end }}