{{- if and .Values.service.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "service.fullname" . }}-ingress
  annotations:
    {{- with .Values.service.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.service.ingress.className }}
  ingressClassName: {{ .Values.service.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.service.ingress.hosts }}
    - {{ if .host }}host: {{ .host }}{{ end }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "service.fullname" $ }}-svc
                port:
                  number: {{ $.Values.service.container.port }}
          {{- end }}
    {{- end }}
  {{- if .Values.service.ingress.tls }}
  tls:
    {{- range .Values.service.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}