{{- if eq .Release.Name "postgres" }}
{{- if eq (.Values.service.dbConnection | default .Values.global.dbConnection | default "k8s") "k8s" }}
apiVersion: ceviche.jcroyoaun.io/v1alpha1 
kind: PostgresSync
metadata:
  name: postgres-dump-manager 
spec:
  repositoryURL: "https://github.com/jcroyoaun/liftnotebook.git"
  databaseDumpPath: "dumps"
  databaseService:
    name: postgres-svc
    namespace: postgres 
  gitCredentials:
    secretName: git-credentials
  databaseCredentials:
    secretName: postgres-credentials
  statefulSetRef:
    name: postgres
  dumpOnWebhook: false
{{- end }}
{{- end }}
