{{- if .Values.service.secretData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.fullname" . }}-secrets
type: Opaque
data:
  {{- range $key, $value := .Values.service.secretData }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}