apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}-svc
  labels:
    app: {{ include "service.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.container.port }}
      targetPort: {{ .Values.service.container.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "service.fullname" . }}
